dataset_config:
  name: GQA_json
  meta_data_name: gqa_sample_2000
  data_path: /./wjh/Crescendo/results/viper_gqa_sample2000_GQA_sample_2000/2024-01-06-all/json
  start: 1491
  batch_size: 13
prompt_file: /./wjh/Crescendo/prompts/viper_GQA.prompt