multiprocessing: True                             # Run the models and samples in parallel
path_pretrained_models: '/.t/pretrained_models/'       # Path to the pretrained models
execute_code: False                                 # Execute the code after generating it. Only applies to main_batch
key_pooling: True

inject:
    inject_html: True                                   # visualize the process
use_cache: False
use_fixed_code: False                               # Use a fixed code for all samples (do not generate with Codex)
fixed_code_file: ./prompts/fixed_code/blip2.prompt  # Path to the fixed code file

detect_thresholds:                                  # Thresholds for the models that perform detection
    glip: 0.5
    maskrcnn: 0.8
    owlvit: 0.1
    GD_BOX: 0.24
    GD_TEXT: 0.24